### ISSUE TITLE
Peer to Peer code review

### ISSUE THREAD

**Issue by abdulrahmanshr75** [BertrandConxy/LeaderBoard-app#4]

**Comment by abdulrahmanshr75** [comment]
Hello @BertrandConxy 🎖️ 
Nice coding structure and styling 🔥 
you did a great job 🥇 
Keep up with the good work ⬆️

**Comment by Kandy-Peter** [comment]
Hi @BertrandConxy,

You did a good job and your code is nice but I would like to suggest you delete the `createGame`  function for a better clean code because it is not needed for the functionality of your project once you get the Id.

**Comment by BertrandConxy** [comment]
Thank you @abdulrahmanshr75  and @Kandy-Peter. I will work on that.
