### ISSUE TITLE
Peer to peer code review

### ISSUE THREAD

**Issue by tariktesfa** [BertrandConxy/LeaderBoard-app#5]
Hello, @BertrandConxy  👋 

You have done a great job so far 🍾 🍾 

To highlight 

- All liner checks are passed 💯 
- You have a professional readme 👍 
- You have used proper ES6 syntaxes. 👍 

But I have only had one suggestion to make your code more professional.

- Please try to add validation for your input that accepts only numbers.

Happy coding 🥳 🥳

**Comment by BertrandConxy** [comment]
Yeah. Thank you.
